# This is a basic workflow to help you get started with Actions

name: CI_Ubuntu

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  repository_dispatch:
    types: 
      - updated-delfem2

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install dependencies
        run: |
          git submodule update --init external/delfem2
          cd external/delfem2
          git pull origin master
          cd ../../

          git submodule update --init external/pybind11          

          git submodule update --init external/eigen
          cd external/eigen
          mkdir build
          cd build
          cmake ..
          cmake --install . --prefix ../../eigenlib

          # sudo apt-get install build-essential cmake
          
          sudo apt-get install libgl-dev


      - name: build_examples (alembic)
        run: |
          echo ########################################
          echo ## build examples alembic
          
          git submodule update --init -- external/Imath
          cd external/Imath || exit
          git checkout main
          git pull origin main
          mkdir build
          cd build || exit
          cmake .. -DBUILD_TESTING=OFF
          cmake --build .
          cmake --install . --prefix ../../Imathlib
          cd ../../../

          Imath_dir=$(pwd)/external/Imathlib
          echo "Imath_dir: ${Imath_dir}"

          git submodule update --init -- external/alembic
          cd external/alembic
          git checkout master
          git pull origin master
          mkdir build
          cd build || exit
          # absolute path is required for CMAKE_PREFIX_PATH
          cmake .. \
            -DUSE_TESTS=OFF \
            -DCMAKE_PREFIX_PATH=${Imath_dir}
          cmake --build . 
          cmake --install . --prefix=../../alembiclib
          cd ../../../          


      # Runs a set of commands using the runners shell
      - name: build
        run: |
          cd src
          mkdir build
          cd build
          cmake ..
          make
          cd ../..

          cd src/opengl
          mkdir build
          cd build
          cmake ..
          make 
          cd ../../../

          cd src/alembic
          mkdir build
          cd build
          cmake ..
          make
          cd ../../../



